<?php
if ($this->serie->isSaved()) {
    $this->redirect();
}

echo $this->header("Edit serie - " . $this->serie->name);
echo $this->buttonLink("Back to overview", $this->url($this->serie->toArray(), "serie-get"));
?>
<div class="tabs">
    <ul>
        <li><a href="#serie-edit">Edit serie</a></li>
        <li><a href="#serie-delete">Delete serie</a></li>
    </ul>
    <div id="serie-edit">
<?php
echo $this->form;
?>
</div>
    <div id="serie-delete">
    <?php
    $this->header()->goDown();
    echo $this->action("delete", "serie", "default", $this->serie->toArray());
    $this->header()->goUp();
    ?>
    </div>
</div>