<?php
$this->headTitle("Microscope");
$microscope = $this->microscope;
printf("<h1>Microscope - %s</h1>", $microscope->name);
?>
<table>
    <tbody>
<?php
echo $this->tableLayout()->row(array("Name", $microscope->name));
echo $this->tableLayout()->row(array("Tag", $microscope->tag));
echo $this->tableLayout()->row(array("Comment", $microscope->comment));
echo $this->tableLayout()->row(array("Suspended", $microscope->is_suspended ? "Yes" : "No"));
?>
    </tbody>
</table>
<?php
$user = Zend_Auth::getInstance()->getIdentity();
$acl = Zend_Controller_Front::getInstance()->getPlugin("MP_Controller_Plugin_Acl")->getAcl();

// kontrola, jestli uzivatel muze editovat mikroskop
if ($acl->isAllowed($user->role, "microscope", "put")) {
    $url = $this->url($microscope->toArray(), "microscope-put");
    
    printf("<a href='%s'>Edit</a>", $url);
}
?>