<?php
echo $this->header("Frames");

echo "<div id='frame-director-controls'></div>";
echo "<div id='frame-container'>";

echo $this->frame()->frames($this->frames, array(
    "actions" => array(
        "frame-get" => array(
            "caption" => "Details"
        ),
        "frame-download" => array(
            "caption" => "Download", 
            "target" => "_blank"
            )
        )
    ));

echo "</div>";
?>
<div id="big-frame">
    <div id="big-frame-wrapper">
        <img src="<?php if ($this->frames->count()) echo $this->frames[0]->getPublicFullPath(); ?>">
    </div>
</div>
