<table>
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Value
            </th>
        </tr>
    </thead>
    <tbody>
<?php
foreach ($this->items as $item) {
    ?>
        <tr>
            <td>
                <?php echo $item->name; ?>
            </td>
            <td>
                <?php echo $item->value; ?>
            </td>
        </tr>
    <?php
}
?>
    </tbody>
</table>
<?php
// nacteni dat
$acl = Zend_Controller_Front::getInstance()->getPlugin("MP_Controller_Plugin_Acl")->getAcl();
$user = Zend_Auth::getInstance()->getIdentity();

$this->header()->goDown();

if ($acl->isAllowed($user->role, "meta", "post")) {
    echo $this->action("post", "meta", "default", array(
    MetaController::REQUEST_PARAM_NAME => $this->metaType,
    MetaController::REQUEST_PARAM_PARENT_ID => $this->parentId
    ));
}
?>