<?php
$this->header("User list");

echo $this->buttonLink("Create new user", $this->url(array(), "post-user"));

// vyhodnoceni akci
$acl = $this->acl();
$user = Zend_Auth::getInstance()->getIdentity();

$actions = array();

if ($acl->isAllowed($user, "user", "getother")) {
    $actions["get-user"] = "Show";
}

if ($acl->isAllowed($user, "user", "putother")) {
    $actions["put-user"] = "Edit";
}

echo $this->user()->users($this->users, array("actions" => $actions));
?>
