<?php
$collection = $this->collection;
echo $this->header(sprintf("Collection %s", $collection->name));

echo $this->buttonLink("Back to serie", $this->url($this->serie->toArray(), "serie-get"));
?>
<div class="tabs">
    <ul>
        <li><a href="#collection-overview">Overview</a></li>
        <li><a href="#collection-frames">Frames</a></li>
    </ul>
    <div id="collection-overview">
<table class="info-table">
    <?php
    $table = $this->tableLayout();
    
    echo $table->row(array("Name", $collection->name));
    echo $table->row(array("Tag", $collection->tag));
    echo $table->row(array("Group name", $collection->group_name ? $collection->group_name : "-"));
    echo $table->row(array("Owner", $collection->username));
    echo $table->row(array("Frame count", $collection->frame_count));
    ?>
</table>
<?php
if ($collection->checkAccess(MP_Db_Table_Row_DataAccess::ACCESS_WRITE)) {
    $url = $this->url($collection->toArray(), "put-collection");
    
    echo $this->buttonLink("Edit collection", $url, array(), true);
}

$this->header()->goDown();

echo $this->comment($collection->comment_html);
?>
    </div>
    <div id="collection-frames">
        <?php
echo $this->action("index", "frame", "default", $this->collection->toArray());
?>
    </div>
</div>