<?php
if ($this->row) {
    $redirector = new Zend_Controller_Action_Helper_Redirector();
    $url = $this->url($this->row->toArray(), "put-collection");
    
    $redirector->gotoUrlAndExit($url);
}

echo $this->header(sprintf("New collection for experiment &QUOT;%s&QUOT;", $this->serie->name));
$this->header()->goDown();

$backUrl = $this->url($this->serie->toArray(), "serie-get");
echo $this->buttonLink("Back to serie", $backUrl);

echo $this->form;

$this->header()->goUp();
?>
