<?php
if ($this->redirect) {
    $redirector = new Zend_Controller_Action_Helper_Redirector();
    $url = $this->url($this->collection->toArray(), "put-collection");
    
    $redirector->gotoUrlAndExit($url);
}

echo $this->header(sprintf("Edit collection &QUOT;%s&QUOT;", $this->collection->name));
$this->header()->goDown();

$backUrl = $this->url($this->experiment->toArray(), "edit-experiment");
echo $this->buttonLink("Back to experiment", $backUrl);

echo $this->form;

if (is_null($this->collection->tag) && $this->collection->checkAccess(MP_Db_Table_Row_DataAccess::ACCESS_DELETE)) {
    echo $this->action("delete", "collection", "default", $this->collection->toArray());
}

$this->header()->goUp();
?>